name: Tag and Release on Push

on:
  push:
    branches:
      - main

jobs:
  tag_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Set up GitHub token authentication
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Get current version
        id: get_version
        run: |
          # Get the most recent tag, fallback to v1.0.0 if none exist
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
          echo "Current version is $TAG"
          # Ensure the tag is in the form v<major>.<minor>.<patch>
          if [[ "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            VERSION=${TAG#v}
            echo "Version extracted: $VERSION"
          else
            echo "Invalid version tag format. Using default version v1.0.0."
            VERSION="1.0.0"
          fi
          echo "::set-output name=version::$VERSION"

      - name: Bump version
        id: bump_version
        run: |
          # Split the version into major, minor, and patch
          IFS='.' read -r major minor patch <<< "${{ steps.get_version.outputs.version }}"
          # Increment the patch version
          patch=$((patch + 1))
          # Reassemble the new version
          NEW_VERSION="v$major.$minor.$patch"
          echo "New version is $NEW_VERSION"
          echo "::set-output name=version::$NEW_VERSION"

      - name: Check if tag already exists
        id: check_tag
        run: |
          # Check if the tag already exists on the remote
          if git rev-parse -q --verify "refs/tags/${{ steps.bump_version.outputs.version }}"; then
            echo "Tag already exists."
            echo "::set-output name=tag_exists::true"
          else
            echo "Tag does not exist."
            echo "::set-output name=tag_exists::false"
          fi

      - name: Create new tag
        if: steps.check_tag.outputs.tag_exists == 'false'
        run: |
          git tag ${{ steps.bump_version.outputs.version }}
          git push origin ${{ steps.bump_version.outputs.version }}

      - name: Create release
        if: steps.check_tag.outputs.tag_exists == 'false'
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.bump_version.outputs.version }}
          release_name: Release ${{ steps.bump_version.outputs.version }}
          body: |
            Automated release for version ${{ steps.bump_version.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}